export type ProfileLocale = 'zh' | 'en' | 'ja';

export function getProfileCopy(locale: ProfileLocale) {
  if (locale === 'ja') {
    return {
      accountLabel: '公開プロフィール',
      accountTitle: '公開プロフィール',
      accountBody: 'ギャラリーで承認済みの公開作品だけを、ひとつの共有ページにまとめます。',
      enable: 'プロフィールを公開',
      disable: '公開プロフィールを停止',
      copyLink: '公開プロフィールのリンクをコピー',
      copied: 'コピーしました',
      copyFailed: 'コピーできませんでした',
      loading: '読み込み中',
      hidden: '公開プロフィールは未公開',
      visible: '公開プロフィールを公開中',
      visibleItems: '表示中',
      interactions: '合計いいね',
      loadMore: 'もっと見る',
      loadingMore: '読み込み中',
      topBadge: '上位',
      galleryCount: ' 件の公開ギャラリー作品',
      galleryMetric: 'ギャラリー作品',
      signinHint: '公開プロフィールを作るにはサインインしてください。',
      publicLabel: '写真家のプロフィール',
      publicTitleSuffix: 'の公開作品',
      emptyTitle: '公開中の作品はまだありません',
      emptyBody: 'ギャラリーで承認された作品がここに表示されます。',
      openReview: '講評を見る',
      backGallery: 'ギャラリーへ戻る',
      unavailable: 'プロフィールを表示できません',
    };
  }

  if (locale === 'en') {
    return {
      accountLabel: 'Public profile',
      accountTitle: 'Public profile',
      accountBody: 'Collect only your approved public Gallery work on one shareable page.',
      enable: 'Enable public profile',
      disable: 'Pause public profile',
      copyLink: 'Copy link',
      copied: 'Copied',
      copyFailed: 'Copy failed',
      loading: 'Loading',
      hidden: 'Currently private',
      visible: 'Live',
      visibleItems: 'Visible',
      interactions: 'total likes',
      loadMore: 'Load more',
      loadingMore: 'Loading',
      topBadge: 'Top',
      galleryCount: 'public Gallery works',
      galleryMetric: 'Gallery works',
      signinHint: 'Sign in before publishing a profile.',
      publicLabel: 'Photographer profile',
      publicTitleSuffix: "'s public work",
      emptyTitle: 'No public work yet',
      emptyBody: 'Approved Gallery work will appear here.',
      openReview: 'Open critique',
      backGallery: 'Back to Gallery',
      unavailable: 'This profile is unavailable',
    };
  }

  return {
    accountLabel: '公开主页',
    accountTitle: '公开主页',
    accountBody: '只把你当前通过审核的公开长廊作品汇集到一个可分享页面。',
    enable: '发布公开主页',
    disable: '停止公开主页',
    copyLink: '复制公开主页链接',
    copied: '已复制',
    copyFailed: '复制失败',
    loading: '加载中',
    hidden: '公开主页未发布',
    visible: '公开主页已发布',
    visibleItems: '当前可见',
    interactions: '总点赞',
    loadMore: '加载更多',
    loadingMore: '加载中',
    topBadge: '精选',
    galleryCount: ' 个公开长廊作品',
    galleryMetric: '长廊作品',
    signinHint: '登录后才能发布公开主页。',
    publicLabel: '摄影主页',
    publicTitleSuffix: '的公开作品',
    emptyTitle: '还没有公开作品',
    emptyBody: '通过长廊审核的作品会显示在这里。',
    openReview: '查看点评',
    backGallery: '返回长廊',
    unavailable: '这个主页暂时不可访问',
  };
}
