import type { Locale } from '@/lib/i18n';

export const GALLERY_UX_COPY = {
  zh: {
    view: '显示',
    columns: '列数',
    auto: '自动',
    oneColumn: '1 列',
    twoColumns: '2 列',
    threeColumns: '3 列',
    full: '完整',
    compact: '紧凑',
    scoreboardTitle: '近期公开作品',
    scoreboardBody: '按当前累计喜欢数展示近 7 或 30 天上架的公开 Gallery 作品。',
    collectionBody: '当前样本不足，先按最近上架整理成发现集合。',
    sevenDays: '7 天',
    thirtyDays: '30 天',
    asOf: '截至',
    photos: '作品',
    authors: '作者',
    viewMore: '查看更多',
    previous: '上一篇',
    next: '下一篇',
    backToGallery: '返回 Gallery',
    unavailable: '暂无相邻作品',
  },
  en: {
    view: 'View',
    columns: 'Columns',
    auto: 'Auto',
    oneColumn: '1 col',
    twoColumns: '2 cols',
    threeColumns: '3 cols',
    full: 'Full',
    compact: 'Compact',
    scoreboardTitle: 'Recent public work',
    scoreboardBody: 'Public Gallery work added in the last 7 or 30 days, ordered by current likes.',
    collectionBody: 'The sample is still small, so this is shown as a recent discovery collection.',
    sevenDays: '7 days',
    thirtyDays: '30 days',
    asOf: 'As of',
    photos: 'photos',
    authors: 'authors',
    viewMore: 'View more',
    previous: 'Previous',
    next: 'Next',
    backToGallery: 'Back to Gallery',
    unavailable: 'No adjacent work',
  },
  ja: {
    view: '表示',
    columns: '列',
    auto: '自動',
    oneColumn: '1 列',
    twoColumns: '2 列',
    threeColumns: '3 列',
    full: '標準',
    compact: 'コンパクト',
    scoreboardTitle: '最近の公開作品',
    scoreboardBody: '直近 7 日または 30 日に Gallery へ公開された作品を、現在のいいね数で表示します。',
    collectionBody: 'サンプルがまだ少ないため、最近の発見コレクションとして表示します。',
    sevenDays: '7 日',
    thirtyDays: '30 日',
    asOf: '基準時刻',
    photos: '作品',
    authors: '作者',
    viewMore: 'もっと見る',
    previous: '前へ',
    next: '次へ',
    backToGallery: 'Gallery に戻る',
    unavailable: '隣接する作品はありません',
  },
} satisfies Record<Locale, Record<string, string>>;

export function getGalleryUxCopy(locale: Locale) {
  return GALLERY_UX_COPY[locale] ?? GALLERY_UX_COPY.en;
}
