import { normalizeLocale } from './locale';

const RETAKE_COACH_COPY = {
  zh: {
    nav: '重拍教练',
    navShort: '重拍',
    label: 'GPT-5.6 Retake Coach',
    title: '选一张原片，开始一次有证据的重拍',
    body: '从历史点评中选出原片，再上传重拍图。GPT-5.6 会按构图、光线、色彩、感染力和技术五个维度比较，而不是把两张照片各说一遍。',
    modelBadge: 'Powered by GPT-5.6',
    steps: ['原片', '拍摄目标', '重拍图', '对比变化'],
    currentStep: '当前：选择原片',
    upcomingStep: '后续步骤',
    target: '拍摄目标',
    dimensions: { composition: '构图', lighting: '光线', color: '色彩', impact: '感染力', technical: '技术' },
    sourceTitle: '选择原片点评',
    sourceBody: '可选择任何已完成的点评。一次重拍结果也能成为下一轮的原片，持续形成进步链。',
    loading: '正在读取你的点评记录…',
    error: '暂时无法读取点评记录。',
    retry: '重新加载',
    emptyTitle: '还没有可作为原片的点评',
    emptyBody: '先完成一次普通照片点评，再回到这里开始重拍对比。',
    firstReview: '先点评一张照片',
    select: '以此为原片',
    score: '原片评分',
    compared: '已是重拍结果',
    historyCta: '开始重拍对比',
    homeTitle: '原片与重拍，不再凭感觉比较',
    homeBody: '选择历史原片并上传重拍图，获得五维改善幅度、画面依据和下一次拍摄清单。',
    homeCta: '进入重拍教练',
    workspaceTitle: '上传这次的重拍照片',
    workspaceBody: '原片已经锁定。上传新照片后，GPT-5.6 会按同一尺度比较两次拍摄。',
    changeSource: '更换原片',
    sourceLoading: '正在加载原片…',
    sourceError: '原片不可访问或点评尚未完成，请重新选择。',
    originalReady: '原片已就位',
    uploadStep: '下一步：上传重拍图',
    originalAlt: '用于重拍比较的原片',
  },
  en: {
    nav: 'Retake Coach',
    navShort: 'Retake',
    label: 'GPT-5.6 Retake Coach',
    title: 'Choose an original. Make the next shot measurable.',
    body: 'Pick an original from your critique history, then upload the retake. GPT-5.6 compares composition, lighting, color, impact, and technique instead of critiquing two disconnected images.',
    modelBadge: 'Powered by GPT-5.6',
    steps: ['Original', 'Target', 'Retake', 'Compare'],
    currentStep: 'Current: choose the original',
    upcomingStep: 'Upcoming',
    target: 'Target',
    dimensions: { composition: 'Composition', lighting: 'Lighting', color: 'Color', impact: 'Impact', technical: 'Technical' },
    sourceTitle: 'Choose the original critique',
    sourceBody: 'Any completed critique can start a retake. A retake can also become the next original, creating a continuous practice chain.',
    loading: 'Loading your critique history…',
    error: 'Your critique history could not be loaded.',
    retry: 'Try again',
    emptyTitle: 'No completed critique is ready yet',
    emptyBody: 'Complete one standard photo critique, then return here to compare a retake.',
    firstReview: 'Critique a photo first',
    select: 'Use as original',
    score: 'Original score',
    compared: 'Retake result',
    historyCta: 'Start a retake comparison',
    homeTitle: 'Compare the original and retake with evidence',
    homeBody: 'Choose a previous frame and upload the retake for five-part deltas, visual evidence, and a concrete next-shoot checklist.',
    homeCta: 'Open Retake Coach',
    workspaceTitle: 'Upload this round’s retake',
    workspaceBody: 'The original is locked. After upload, GPT-5.6 will compare both attempts on the same scale.',
    changeSource: 'Change original',
    sourceLoading: 'Loading the original…',
    sourceError: 'The original is unavailable or its critique is incomplete. Choose another one.',
    originalReady: 'Original ready',
    uploadStep: 'Next: upload the retake',
    originalAlt: 'Original photo selected for retake comparison',
  },
  ja: {
    nav: '再撮影コーチ',
    navShort: '再撮影',
    label: 'GPT-5.6 Retake Coach',
    title: '元の写真を選び、再撮影の変化を測る',
    body: '講評履歴から元の写真を選び、再撮影をアップロードします。GPT-5.6 が構図・光・色・印象・技術を同じ尺度で比較します。',
    modelBadge: 'Powered by GPT-5.6',
    steps: ['元の写真', '撮影目標', '再撮影', '比較'],
    currentStep: '現在：元の写真を選択',
    upcomingStep: '次のステップ',
    target: '撮影目標',
    dimensions: { composition: '構図', lighting: '光', color: '色', impact: '印象', technical: '技術' },
    sourceTitle: '元の講評を選択',
    sourceBody: '完了した講評から選べます。再撮影結果を次の元写真にして、練習の連鎖も作れます。',
    loading: '講評履歴を読み込んでいます…',
    error: '講評履歴を読み込めませんでした。',
    retry: '再読み込み',
    emptyTitle: '元にできる講評がまだありません',
    emptyBody: 'まず通常の写真講評を1回完了してから、再撮影比較を始めてください。',
    firstReview: '先に写真を講評',
    select: 'この写真を元にする',
    score: '元のスコア',
    compared: '再撮影結果',
    historyCta: '再撮影比較を始める',
    homeTitle: '元の写真と再撮影を、根拠とともに比較',
    homeBody: '過去の写真を選び、再撮影をアップロードして、5項目の変化・画面の根拠・次の撮影リストを受け取ります。',
    homeCta: '再撮影コーチを開く',
    workspaceTitle: '今回の再撮影をアップロード',
    workspaceBody: '元の写真は選択済みです。アップロード後、GPT-5.6 が同じ尺度で2回の撮影を比較します。',
    changeSource: '元の写真を変更',
    sourceLoading: '元の写真を読み込んでいます…',
    sourceError: '元の写真にアクセスできないか、講評が未完了です。別の写真を選んでください。',
    originalReady: '元の写真を設定済み',
    uploadStep: '次へ：再撮影をアップロード',
    originalAlt: '再撮影比較に選んだ元の写真',
  },
} as const;

export function getRetakeCoachCopy(locale: string) {
  return RETAKE_COACH_COPY[normalizeLocale(locale)];
}
