export const siteConfig = {
  name: 'PicSpeak',
  url: 'https://www.picspeak.art',
  title: 'PicSpeak | AI Photo Critique and GPT Image 2 Visual References',
  description:
    'PicSpeak critiques photos across composition, lighting, color, impact, and technique, then creates GPT Image 2 visual references for the next shoot.',
  keywords: [
    'AI photography critique',
    'photo feedback',
    'photo analysis',
    'photography review',
    'image critique',
    'composition feedback',
    'lighting analysis',
    'photo scoring',
    'AI photo review',
    'photography improvement',
    'photo critique online',
    'AI photo analysis',
    'photography tips',
    'photo composition',
    'photography feedback tool',
    'image quality analysis',
    'AI image generation',
    'GPT Image 2',
    'AI visual references',
    'AI image prompt library',
    'photo inspiration generator',
    '摄影点评',
    'AI摄影',
    '照片分析',
    'AI图像生成',
    '摄影参考图生成',
    'AI写真批評',
    'AI画像生成',
  ],
  googleSiteVerification: 'uPzmX8kYSDzOWm7iBz-dty4It12mMcIVUOPPwWmLGnM',
  logoImage: '/logo.png',
  logoImageWidth: 180,
  logoImageHeight: 180,
  ogImage: '/og-product.png',
  ogImageWidth: 1200,
  ogImageHeight: 630,
  repositoryUrl: 'https://github.com/AsaZhou923/picspeak',
  organizationId: 'https://www.picspeak.art/#organization',
  websiteId: 'https://www.picspeak.art/#website',
  editorialPolicyPath: '/editorial-policy',
  social: {
    x: 'https://x.com/Zzw_Prime',
    githubProfile: 'https://github.com/AsaZhou923',
    productHunt: 'https://www.producthunt.com/products/picspeak',
  },
  author: {
    id: 'https://www.picspeak.art/author/asa-zhou#person',
    name: 'Asa Zhou',
    alternateName: ['@Zzw_Prime', 'AsaZhou923'],
    jobTitle: 'Founder and Lens Notes editor',
    description:
      'Builds PicSpeak and writes Lens Notes about AI photo critique, composition, lighting, color, and repeatable review workflows.',
    email: 'xavierzhou23@gmail.com',
    knowsAbout: [
      'AI photo critique',
      'photography composition',
      'lighting analysis',
      'color feedback',
      'repeatable photography practice',
      'GPT Image 2 prompt examples',
    ],
  },
} as const;
