export const siteConfig = {
  name: 'PicSpeak',
  url: 'https://picspeak.art',
  title: 'PicSpeak | AI Photography Critique and Photo Feedback',
  description:
    'PicSpeak uses AI to critique your photos across composition, lighting, color, impact, and technique. Get instant professional-grade feedback to improve your photography skills.',
  keywords: [
    'AI photography critique',
    'photo feedback',
    'photo analysis',
    'photography review',
    'image critique',
    'composition feedback',
    'lighting analysis',
    'photo scoring',
    'AI photo review',
    'photography improvement',
    'photo critique online',
    'AI photo analysis',
    'photography tips',
    'photo composition',
    'photography feedback tool',
    'image quality analysis',
    '摄影点评',
    'AI摄影',
    '照片分析',
  ],
  googleSiteVerification: 'uPzmX8kYSDzOWm7iBz-dty4It12mMcIVUOPPwWmLGnM',
  ogImage: '/logo.png',
  repositoryUrl: 'https://github.com/AsaZhou923/picspeak',
  social: {
    x: 'https://x.com/Zzw_Prime',
    githubProfile: 'https://github.com/AsaZhou923',
  },
  author: {
    id: 'https://picspeak.art/#asa-zhou',
    name: 'Asa Zhou',
    alternateName: ['@Zzw_Prime', 'AsaZhou923'],
    jobTitle: 'Founder and Lens Notes editor',
    description:
      'Builds PicSpeak and writes Lens Notes about AI photo critique, composition, lighting, color, and repeatable review workflows.',
    email: 'xavierzhou23@gmail.com',
  },
} as const;
